### ISSUE TITLE
no default bird.conf

### ISSUE THREAD

**Issue by sbilly** [jvoss/zerotier-bird-router#1]
Using command 
`docker run -ti --rm --name zerotier-bird-router --device=/dev/net/tun --cap-add=NET_ADMIN -v /zt:/var/lib/zerotier-one -v /bird:/opt/bird/etc jpvoss/zerotier-bird-router:latest` to start docker, but it print the following logs and exit.

```
Starting ZeroTier
Starting BIRD
bird: Unable to open configuration file /opt/bird/etc/bird.conf: No such file or directory
bird: Unable to open configuration file /opt/bird/etc/bird.conf: No such file or directory
```

**Comment by jvoss** [comment]
Much like the Zerotier configuration, BIRD configuration is designed to be mounted to `/opt/bird/etc`. For example, a local file can be mounted as the BIRD configuration with:

```
docker run --device=/dev/net/tun --cap-add=NET_ADMIN \
         -v ./bird.conf:/opt/bird/etc/bird.conf \
         jvoss/zerotier-route-server
